-- Phase 2: Add email preference columns + notification preference expansion
ALTER TABLE notification_preferences
  ADD COLUMN IF NOT EXISTS email_weekly_briefing BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS email_task_digest BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS email_lifecycle BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS email_milestones BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS preferred_notification_time TIME DEFAULT '08:00',
  ADD COLUMN IF NOT EXISTS mood_reminders BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS milestone_notifications BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS onboarding_nudges BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS re_engagement_emails BOOLEAN NOT NULL DEFAULT TRUE;
